# Generated by Django 5.1.1 on 2024-10-14 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipies',
            new_name='Recipie',
        ),
        migrations.RenameField(
            model_name='recipie',
            old_name='recipe_desc',
            new_name='receipe_desc',
        ),
        migrations.RenameField(
            model_name='recipie',
            old_name='recipe_img',
            new_name='receipe_img',
        ),
        migrations.RenameField(
            model_name='recipie',
            old_name='recipe_name',
            new_name='receipe_name',
        ),
    ]
